export enum OtSegmentType {
  WEEKDAY_DAY = 'WEEKDAY_DAY',
  WEEKDAY_NIGHT = 'WEEKDAY_NIGHT',
  WEEKEND_DAY = 'WEEKEND_DAY',
  WEEKEND_NIGHT = 'WEEKEND_NIGHT',
  HOLIDAY_DAY = 'HOLIDAY_DAY',
  HOLIDAY_NIGHT = 'HOLIDAY_NIGHT',
}
