export const LEAVE_CONSTANTS = {
  HOURS_PER_DAY: 8,
  HALF_DAY: 0.5,
  MAX_ANNUAL_LEAVE_PER_YEAR: 12,
  MAX_UNPAID_LEAVES_PER_YEAR: 30,
  MIN_LEAVE_DAYS: 0,
  SLOT_MORNING: 1,
  SLOT_AFTERNOON: 2,
} as const;